# Generated by Django 4.2.3 on 2023-07-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='doj',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
