# Generated by Django 4.2.3 on 2023-07-18 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRMApp', '0005_rename_name_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_spec', models.CharField(choices=[('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Cardiologists', 'Cardiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Critical Care Medicine Specialists', 'Critical Care Medicine Specialists'), ('Dermatologists', 'Dermatologists'), ('Endocrinologists', 'Endocrinologists'), ('Family Physicians', 'Family Physicians'), ('Gastroenterologists', 'Gastroenterologists'), ('Gastroenterologists', 'Gastroenterologists'), ('Geriatric Medicine Specialists', 'Geriatric Medicine Specialists'), ('Hematologists', 'Hematologists'), ('Oncologists', 'Oncologists'), ('Ophthalmologists', 'Ophthalmologists'), ('Pathologists', 'Pathologists'), ('Pediatricians', 'Pediatricians'), ('Physiatrists', 'Physiatrists'), ('Plastic Surgeons', 'Plastic Surgeons'), ('Radiologists', 'Radiologists')], max_length=200)),
                ('doc_contact', models.CharField(max_length=100)),
                ('doc_location', models.CharField(max_length=100)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
