# Generated by Django 4.2.3 on 2023-07-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0007_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='d_schedule',
            new_name='Booking_schedule',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='d_time',
            new_name='Booking_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='d_name',
            new_name='Doctor_name',
        ),
    ]
