# Generated by Django 4.2.3 on 2023-07-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0008_rename_d_schedule_appointment_booking_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRMApp.product')),
            ],
        ),
    ]
