# Generated by Django 4.2.3 on 2023-07-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0009_listproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listproducts',
            old_name='prod_list',
            new_name='user_name',
        ),
    ]
