# Generated by Django 4.2.3 on 2023-07-19 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0010_rename_prod_list_listproducts_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Selector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRMApp.appointment')),
            ],
        ),
    ]
