# Generated by Django 4.2.3 on 2023-07-20 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0012_dealdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealdetails',
            name='Date_of_order',
            field=models.DateField(default=datetime.date(2023, 7, 17)),
        ),
    ]
