# Generated by Django 4.2.3 on 2023-07-26 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0014_doctorvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaysschedule',
            name='Date_Selector',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='TodaysSchedule',
        ),
    ]
