# Generated by Django 4.2.3 on 2023-07-26 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0015_remove_todaysschedule_date_selector_delete_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealdetails',
            name='Date_of_order',
            field=models.DateField(default=datetime.date(2023, 7, 26)),
        ),
    ]
