# Generated by Django 5.0.4 on 2024-05-07 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0016_alter_dealdetails_date_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealdetails',
            name='Date_of_order',
            field=models.DateField(default=datetime.date(2024, 5, 7)),
        ),
        migrations.AlterField(
            model_name='dealdetails',
            name='Quantity_Ordered',
            field=models.IntegerField(),
        ),
    ]
