# Generated by Django 5.0.4 on 2024-05-07 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0017_alter_dealdetails_date_of_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealdetails',
            name='Quantity_Ordered',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
