# Generated by Django 5.0.4 on 2024-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMApp', '0019_alter_dealdetails_quantity_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealdetails',
            name='Quantity_Ordered',
            field=models.PositiveIntegerField(),
        ),
    ]
